spring.application.name=inventory-management

#CONFIGURACION BASE DE DATOS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${BD_URL}
spring.datasource.username=${BD_USER}
spring.datasource.password=${BD_PASSWORD}


@CONFIGURACIONES DE JWT
security.jwt.private.key=${PRIVATE_KEY}
security.jwt.user.generator=${USER_GENERATOR}

springdoc.swagger-ui.operationsSorter=method