spring.application.name=inventory-management

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${BD_URL}
spring.datasource.username=${BD_USER}
spring.datasource.password=${BD_PASSWORD}

springdoc.swagger-ui.operationsSorter=method